server:
    port: 8101
spring:
  application:
    name: psl
  banner:
    #image:
    location: classpath:bander.txt
  datasource:
    druid:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@192.168.6.66:1521:orcl
      username: user_cert
      password: user_cert
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
mybatis:
  #映射配置文件路径
  mapper-locations: classpath:mybatis/mapper/*.xml
  #核心配置文件路径
  config-location: classpath:mybatis/mybatis-config.xml
logging:
  config: classpath:logback-spring.xml
  file:
    path: classpath:logs
spring.resources.static-locations: classpath:static/,file:static/
